<?php

namespace AppBundle\Repository;

/**
 * auctionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class auctionsRepository extends \Doctrine\ORM\EntityRepository
{
}
